apiVersion: batch/v1
kind: Job
metadata:
  name: inventory-migration
spec:
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
        sidecar.istio.io/inject: "true"
      labels:
        istio.io/rev: default
    spec:
      containers:
        - name: inventory-migration
          env:
            - name: ISTIO_QUIT_SIDECAR_ON_EXIT
              value: "true"
