apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/albersg/atlas-inventory-service
    newName: ghcr.io/albersg/atlas-inventory-service
    newTag: main
  - name: ghcr.io/albersg/atlas-web
    newName: ghcr.io/albersg/atlas-web
    newTag: main
