apiVersion: ENC[AES256_GCM,data:ICE=,iv:9wiMU45ftr8Ip3zd0UyMbIv1OZ4N//3Q29W9q+YUGRQ=,tag:gLIwF4bKShpuILdE344AOg==,type:str]
kind: ENC[AES256_GCM,data:rUQc/D1I,iv:zZeWpijP/FZyJY8L7nMxumM3fA9ZjO0c3yjgbbUgdEI=,tag:4I/LuyZ6MfijAI26Jzpq4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IyvBEfwBmhuSvy2Ea+SlchM=,iv:oZrNaf50LIGs9i+YDmlJBUIMN/YH+s530uNESwFwbw4=,tag:9rceBUB2ZeBbnXRD1Vjypw==,type:str]
    namespace: ENC[AES256_GCM,data:8vrJA6aDFByktO4PAzM=,iv:eHhdHw+UORrpx2yzCNtvbRF9eL/xQgMCRURkotVau2c=,tag:LcAjsZCr95/Kl3KkR1+92w==,type:str]
type: ENC[AES256_GCM,data:Zn2YxIao,iv:4GDwIZI2R8LJ99u9d4404qeXUN1/pJWy2wPM9uprxOg=,tag:InXCPRUbSoa5oeI5pOEa3w==,type:str]
stringData:
    INVENTORY_DATABASE_URL: ENC[AES256_GCM,data:3GkuTlH/BBfgf5g8X2c/YyVkXc26HLIL6HDnyxWKMyKjTVquXLpHip2L4nj7n90L2PIH+wVHP65unXzg35iIbNulSYEfw1db1k31tw==,iv:194abAXJm72wFpPxP5CBOMyVtOy+Rx8khTH2bfRawsc=,tag:MdvzrV+ghWQftD2H+10UBA==,type:str]
sops:
    age:
        - recipient: age18p2u2yekx32mhdaea8cpxhvzzld4awa58auh9tdh8wat46pwge2sldmk9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TmtVQmlLUDRYWGZsSFJ5
            SUVjaEE2dk0wejZ4eGxIRWtKWVp0QTIzdndNCitqWCtRcFhPVzZ1WmI2TjdqUXd5
            dTkvaHRtRjA2dWYyZk9ORGk4Unh0aGsKLS0tIDNuemhNTGJOMW1tQ3B0UlNuY0ZR
            bGt2Y0V6UTlFa3VSVGZOR2czOXhROEUKhZ1FYZwezwaTiSvDefA3djVPhVwTnBrP
            wLzlRtgdgQbdIsEHcRpG3lkodfksY0ThM1j6j6XAZ9a2b7z1bwrTXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:10:51Z"
    mac: ENC[AES256_GCM,data:X4/ZugwWnh87bk5o3rQwostfvNh9cmZTOHTpbovaJzY4z6mFPIybsaAXanGC/kdoVU/y6wcvgHeK7ai46jtNV4a4y2BwBRFXgucvCa7QJ+PAtjI97byGTZ/hINtmHqEo8j5zD0Pf4jH0OeZXh7bg2GUzU1iFbY5I7K+qxOugnCk=,iv:YabwUJXRtHkIZI1bOXqRm/m4pTbLyyn0tFELRiROCCE=,tag:vE/R4dF9rex+p+sS1yRUbA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
