apiVersion: ENC[AES256_GCM,data:0hs=,iv:/jH/XPLymXjedNwlcUwy92fmynPiOz4Epn3U9PhP2T4=,tag:XJWzpXkaLPaVX1ltAwNNUg==,type:str]
kind: ENC[AES256_GCM,data:QXHEyEs1,iv:Q6cxFG2+B16Vj7SkOgzp5Bueblv2UdK/mtZj3ZCeDRk=,tag:xRkxmPKr07Pkf/IsNz+cjg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UyaH43geK8yXhdT42Sfl/fc=,iv:OaGQXR6zGOBpjG2oPgXzs+ZVb/NYj995JMIDbuDfOpU=,tag:93A3a0V3Cnd/E+UnjTAW6g==,type:str]
    namespace: ENC[AES256_GCM,data:DU9ZYA2rWacTcHZHZzg=,iv:vWNzdMJCL9tn6voWLPPiTEfcSyMxnP792JaPjZKwya0=,tag:Tg7kv3Xjy93lL8bOD3is0g==,type:str]
type: ENC[AES256_GCM,data:Fmw/AAkx,iv:n3uPISv0u+N9/nTVRBIAed8nleM5kXygNA6fEt/g488=,tag:s+TiPUEnxGS8P8+I8GW6ng==,type:str]
stringData:
    INVENTORY_DATABASE_URL: ENC[AES256_GCM,data:XOwZjxycOE8zOD8zDW12JX59LO1n67HuOHNq6nQvdQq52swv8hROmSQ6atXHZ+4gAjNJzb5u2EHGxb7KWZyqamIWoQwEG4AynmyCRio6cqeA,iv:fVZcxyNCtpMLipx+lIBZKZLQ1WMKKJ/vYs+ena6zd2o=,tag:nzkZ9D/iXJ8IsohdQdXL1w==,type:str]
sops:
    age:
        - recipient: age18p2u2yekx32mhdaea8cpxhvzzld4awa58auh9tdh8wat46pwge2sldmk9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISFRUbWliTEZvYUxIZ0wz
            MXdPMGJ3RCtpdEFuNElhUXg5bldlVlFIdkhRCmRKWmdPRHoyR2VlU0QzeXc2OEg1
            Z2VUaUV3VTdKUnk5eTJWejBQOU1VRTQKLS0tIFNKRWJMbmhSNy9FblVsQklURUxY
            K1JDa2oyTFF1NGZ5M1pyL0JXdWJ3NGcKDQOzMnXMM1oVpc33AXo0NZebNjnOGCMk
            9BGL9X2yb/Y00yHo8TobPxFrvOCJdhr61Wjt8csPC1mahgu9aisNHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:20:40Z"
    mac: ENC[AES256_GCM,data:1vWq6hupC5uMRmLECxLuRWvnPqtwc15+BUfeWzAJz3uEdUhE/3aSelgVGLSef3WV5YxG1nPz025TSwhOUEXeRzJ667DexP87YQc1gFrO2dq5j64RkxIfMiBd8tXMRs8AazdkpKcwT4U95tOQ/cspSZBY91L4T15U6X36GJbCL/c=,iv:Vjl26w1n4YLSjMG4QWWyEfVIgkKB4mOr44Jt+AbTWls=,tag:A9SyTWGh+yZKtDDBUPngwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
