apiVersion: ENC[AES256_GCM,data:R1Y=,iv:r0C63/mrSjAct7wR3pshYnkJgkI5R2pVA+snqoK4apA=,tag:HJmmxTzb7+7FLXClJV9QmA==,type:str]
kind: ENC[AES256_GCM,data:ajvZpGWw,iv:t3C689SPU6eJAIDfUqzOzuSqpND/4RAM+a2g1nCKsQQ=,tag:aCBhP1ZRvc7H0tjHEOUMsw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1uSARqg7SM7esQFtpMQw,iv:VVnNHpGm8II6AYfDVK9DGTKjlLrvnzmpl4o7arae8iM=,tag:tWU0FMSyVEpy/RGxxrz8zQ==,type:str]
    namespace: ENC[AES256_GCM,data:DfcLdu+La5h/5Nv5pGQ=,iv:xwzC6JqnoTcuSdQoa+wLMFpIHmKQno3GSgWYXvdP2Gc=,tag:+MAndGNbFFtpTaWOreSjTA==,type:str]
type: ENC[AES256_GCM,data:0IGToq2a,iv:T0vBTeeEeFPeJeTezyNQYY+Xpko1XRj/mDcxQuGoroE=,tag:20Te0Zw7gUkKc8tKmCW1pQ==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:YOACtg8dH1bu,iv:YjmEHTSykDLEzegPQ6c8Oe+Ij/78BE3BjaCkc95Qm6c=,tag:9OR3OJYjooFQkRRygeejOA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:LgoAUAAz8tKrIk6CGg==,iv:U5A9gj6NOD7frTyvxsoa8VUeDBotHaYqGR9U7N4Qv1Q=,tag:9cYQGkW3DYLnciY4LyplPg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:a+Sl45vTperuHWtynRg7YefTKTgYNw==,iv:m6n3vinPhaYjgkuJ64+HYrqUg5YOoeL4JCubfwAChmg=,tag:63LMUgjXrZ6aCR2hfh0gNA==,type:str]
sops:
    age:
        - recipient: age18p2u2yekx32mhdaea8cpxhvzzld4awa58auh9tdh8wat46pwge2sldmk9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTGpxeHFpR0U2SEZBZnRa
            MG90V2hBWGZMS2paTjNodTFPR0J3NCtoUkFnCkIxTDBIam9ZeGZUOG5USDhzYzJ3
            MkMrQ1l5NWh3bGRJZU91VWhpANDYrejAKLS0tIC9kM2orK2U3c3N4VlBWNnVSajUx
            U2VNRmNHaWtvSWRub1h5R25KTER4QTQKynVs6LhsA9+LCauYjZDtzpikZpWI1Jwz
            A7O/WDypBpLn3V6V7oKRROAy0FRxDUXLFfE9DyeFFaQUnCeIr3QdCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:20:40Z"
    mac: ENC[AES256_GCM,data:tbtuIXXcAp5GjVCu1phkgdSlv59SVLAxEgXONRIutKj/f4+49Ev5Kc0hd5KBrsMEfffx/HnvdaO35fnTyQMXsY+z09Op7io8gViAqPYFKpTij8lIZ3Mf8cHREgpINjXLyfb2o6buUOC2+x73K7hvZx6dNLc1Og6A5vKRNmeAkgA=,iv:wwjoNgXmzQ0qzRPKgnVOMOMleVX+Fuk+zs2PwAuyOqc=,tag:3GLGdDsK7weA3rMMMGMzkw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
