apiVersion: ENC[AES256_GCM,data:dbc=,iv:JUPLv4ASjwluLip1r3kOur1+jDttl0QN2aBQrL6c67w=,tag:2vzD6x3MktrVcx4I4FSVwg==,type:str]
kind: ENC[AES256_GCM,data:0dMxPTZt,iv:yDv6N5tzIJpLjNI2BJ3a3q7NOX+Ts+qC8ObuNdQizSo=,tag:5agcUEal9Hr9W+0CHymNwQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KSkLnnoa6WKziOQQ6D8P,iv:JLQBiA2RC8yIzI9unkdUhpJqMDcg8JXZGnLIyIj64rg=,tag:AgQTnE5U1r5AjHo3yrgkuA==,type:str]
    namespace: ENC[AES256_GCM,data:gf5WtG4wBJYzA7nZMgs=,iv:drilz9DKSh6puYv9UTnr5f03LhQq9n9zMJJuU4mQ6+4=,tag:AB6ESbluhYO+zl0K+CEaoQ==,type:str]
type: ENC[AES256_GCM,data:YdyWcLRp,iv:sNZjzVmIdB5RRW18NI0ZAHc+OunxIKHqOaS+tlSCiOE=,tag:mCIL4QsEJm56k1UoBEtnhw==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:eFGybSu9FOJB,iv:qsM26A5suqXZTUrEpPHiLNoiAs/cgCIOSZY8Gccfm9g=,tag:CrLQcPJXlu/32vHO1vMbgg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:9WjBPrZLcxOgJ5Cr4A==,iv:9yjJbqaA3ZQ9ZdnT0RBhMQd5kqS2TtP8Ae2YcUiNEEQ=,tag:eF84JRYPbRwcUD8yFb3SaA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Ij7jXjeVeWg3ZgktqcPnr+w=,iv:YdZIiP8ZSQ1BQEcWedHnRATQMMQGQsBBk/islzEIx1A=,tag:vEjeXjLPgIYs1VFMYIW5Hg==,type:str]
sops:
    age:
        - recipient: age18p2u2yekx32mhdaea8cpxhvzzld4awa58auh9tdh8wat46pwge2sldmk9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WHRLdEdtaUx2dEhiRkpX
            SUExMnVIa2Qzd2w4UHV1UTBSZVdNekpKQWswClY1QTBIWVlkbkNCaFpPSGdtSGpU
            WUhra3JLa0MrRHhTMGwySUFEMFkrZlkKLS0tIDF6Y1Z0N2ZvVy9Pejk0ZWdSc3c4
            WGkxOWJWajFrNUZDWTdWbkdyMDBKcVkKgjSpYX4bgcZgLs1mJOR16xuxvT0C89BT
            +QoToy49qbafRph0t5ovErVtgJ1oaNYdMkSGxbGDVrMLOZ3HQLC0Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:10:51Z"
    mac: ENC[AES256_GCM,data:F9gsF/uB+0F3SHFiD3BfbX8MKiepYa7CNusbqAqthvdZnK9YDVfVnnAFlEp0cS3OgAtotzWl3RNV1rTSrWo7XaCxmHRlK+J6GHp4e+X5071P9fvedfj/QB1mrmjGhh+owusgE64kEoLWYVxjGjn8SQxpiKiR6Fngrv17WbMqKw0=,iv:qaXYF9ROm0gdHbnPoZdKbHzfCtosN05ztK9XVpY6jBc=,tag:MUeJ9YiFKJPx329Z8hLGqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
