apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config/inventory-config.yaml
  - workloads/inventory-migration-job.yaml
  - workloads/inventory-service-deployment.yaml
  - networking/inventory-service-service.yaml
  - resilience/inventory-service-pdb.yaml
  - resilience/inventory-service-hpa.yaml
  - workloads/web-deployment.yaml
  - networking/web-service.yaml
  - resilience/web-pdb.yaml
  - resilience/web-hpa.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-allow-dns-egress.yaml
  - networkpolicy-web.yaml
  - networkpolicy-inventory-service.yaml
