fullnameOverride: atlas-platform-istio-ingress
labels:
  istio.io/rev: default
autoscaling:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
service:
  type: LoadBalancer
