apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlas-platform-staging

resources:
  - namespace.yaml
  - limitrange.yaml
  - resourcequota.yaml
  - ../../base
  - ../../components/in-cluster-postgres

generators:
  - ksops-generator.yaml

components:
  - ../../components/images/staging
  - ../../components/mesh/istio

patches:
  - target:
      kind: ConfigMap
      name: inventory-config
    patch: |-
      - op: replace
        path: /data/INVENTORY_APP_ENV
        value: staging
  - target:
      kind: Deployment
      name: inventory-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: web
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Job
      name: inventory-migration
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
