apiVersion: ENC[AES256_GCM,data:TzM=,iv:Z1eVRzcluDcwEfif5xZQRarrs8o0OzslkOEt/NOP7X8=,tag:Oz4g9yh1uWo9ZBTlupW3sw==,type:str]
kind: ENC[AES256_GCM,data:D5cpaenH,iv:b9o+W4xETqy7j1vlq8EyKVrfYmFqtVNG/QbFzdOnQNw=,tag:bv0Sogv/gLbXH7TuqvSSFQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:d4zBRo0QQkxt+DoF0Z+sx4M=,iv:2qCVzGVyiv5prK3l0Yaq8t3JdxUhe/6Stsv1ZsUFHKI=,tag:AlUf770Xd6hFTGf32yaq4g==,type:str]
    namespace: ENC[AES256_GCM,data:bd5T/yw9mWfRx1uwLcI=,iv:jkQTlpX27GINIGCjnUvIWIWUL+iPfrU7kSxGUYqwJms=,tag:IapjS6JewMsZnX02xJKF1g==,type:str]
type: ENC[AES256_GCM,data:F2WORLUT,iv:/fn4AeQ3tdQ/2/iyDQ+YAJur9Kmh+UO8dmkfKGPAp00=,tag:QkXzdNy+Klv+RFeQg3moYw==,type:str]
stringData:
    INVENTORY_DATABASE_URL: ENC[AES256_GCM,data:AoAR61wgfbFbrrswJp1naZMma4bXdYVWnhMDOxvzOy8YHIZ+SwOJ3XiBptJPOikvU5ZYGRcP1eMs/WghfBXgjQGk+d4KGwr0QEjINyROHUl56Q==,iv:FcsL2xWI2L9/fljdSDhGA6Jyt1XNIg1rW2awo/F+g5Y=,tag:GMF47rwjH65/8W27TeeMog==,type:str]
sops:
    age:
        - recipient: age18p2u2yekx32mhdaea8cpxhvzzld4awa58auh9tdh8wat46pwge2sldmk9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYllDdCtTZjNrMThQcW1j
            MWNKYVlGcGFpejJ5VjAvd0FKUVEzZVJobEV3CnlSNlg3NERLRmx2OTRCNmp1UXFG
            cXBBdDRTZEndZzhka2J0SjhaYllBRDgKLS0tIGExTXBkUEdiVWQ3TUJxcVBtM002
            NlhDdzJaOGZ6bHRUUFUvMGNoQXJ0L00KiDu8gmVOBjfXYe2ZC8K3/NgHzuW6IYVD
            0OGJP2GPQhV/nMcjEh+Py0qx8rH65VWEVDzXbi+8ICJt2CE4c4iwSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:20:40Z"
    mac: ENC[AES256_GCM,data:LidZ6xXfOYw7Lpk0QA6q61qdBi41xxLZ04LXKDdhnfUFnw9cFRGq0aPy7OX7CSd2gmEiDXbmg9zrdVOu9iBKnpGT5UDfLqtIUwXGJt3XsacGyNIqkb2WwvquC4EKSUQJV7Sg1W0SM3Eby+EMQlOcsLqYYFef9ay0xybUjBlXgWA=,iv:aKEiWcHsFFmMUbMULyQP6hnA7TBY/ZekhRbpkWlBLhk=,tag:BVqCsV43TRWWgJQBC2HZkA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
