apiVersion: ENC[AES256_GCM,data:ILs=,iv:goEtVgFoag7W7GG/5hHtGtSufdqfvYwHeNhKh9key88=,tag:pha4lbcfcAYOIpf9pGAMMg==,type:str]
kind: ENC[AES256_GCM,data:Wuz05QZv,iv:aVk/dxK6IANiHGq9Ki80qn1kC59tRJJlTa76vTgyZZY=,tag:8wLpMor9n7ujBSJ8HBOejg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SYqdLeUvHYUyg08iFXKBqTI=,iv:dE9q3YUp+pwR0OxzyH1nXU6Fvx3WnD/hCkq6p5NNbwk=,tag:Ej2bevbYIzcgha4wdhLX6Q==,type:str]
type: ENC[AES256_GCM,data:UTwj3Imz,iv:C4Nx+SKqfe3CTzEGvXj506WDkJJI8yTxYygmZ/ZWhsw=,tag:FOhYIVTf08w+2abdmwcr8g==,type:str]
stringData:
    INVENTORY_DATABASE_URL: ENC[AES256_GCM,data:JtU1byCGoFYUfHt9ofzvlDyksfVPBjmZxfbbLhrxx3ak7ftmiIM0Si2GM7q1KUB+/Ox7G/aw61Zz5p0Yns53nzfd9uETXz3UkN1bHZLDzoYYO6rks+k=,iv:qsag4BNnIcWuyDWRxC5cE4vpphRw+5QLm1rfWF9ts4A=,tag:+VOQu8BIknz69boXy7/6Xw==,type:str]
sops:
    age:
        - recipient: age1t23p7nly2j9awclcj7fh0c9yu3u3qt3sz9fmkryq7tenwyv9ncmq73tggy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTkt3SU94U3ZLL04yTnBv
            dVR6bVFaM1hyblpscHVKSVZMc1pEVUZnNkNvCnBZUHJaSi9FQ001bWtUNkM1cllH
            VnRXTkZwTDQyVjIrNFc4WGltUEd4S2MKLS0tIDYwVUowTkVMelZ3eXRZQ0FkaHNO
            blpWdXgrak56UDdCM243VDNXQzFmeGMKM78VRXhLooELqyohS7lf1YG6VeXcBS82
            VI+Ey4ZJoCaZjhroPDE5zyyTfsTVLhxpEpJm1zc27sksbQgRTO0pIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T14:34:58Z"
    mac: ENC[AES256_GCM,data:RpxOe3Q2S5lQZvCn7uFsWHyhoHirF1Iw1E003B0JLXE0dwhp/uXQTgPbI7uDe9u5oHGhPo3suGKZG8YxPcYqN7SQV/ikyCn8cSqnKTAfGRodrrnQIMU67n5VWC6pLChmvDX1cgGSDx/uBpuBmHUf8FEmYaGWUPXc7USH512ZnvA=,iv:aeynxEdGxtV6PKx3qY1bN2B+PeQ3bTMa/2S5XpTEfl8=,tag:10/ik94nnqOBTgJIctK8JA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
