apiVersion: ENC[AES256_GCM,data:BRQ=,iv:kFJ7RYPeI4MWUezb2rJziY34OGCHDHzM0rT/LaDBujA=,tag:Up2LV0skLPqjhSDeaCYE9Q==,type:str]
kind: ENC[AES256_GCM,data:JLrvyH+F,iv:E+wJNiia+EKcn/SlGxxvISQPsNfCH2/G94zyqtZ3Fz8=,tag:/hdkhOwtOyBiMLugRKYxFQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ucr9DKK+XiCkifs/gl9U/cU=,iv:i9YJnDzBrm+NPTxL6TdEj6UWYHo2vEXvuse8lGmWqeg=,tag:32FPwxHwfMuopq5V1s+Ncw==,type:str]
    namespace: ENC[AES256_GCM,data:ftpvFfOtgpgOxQHEpwY=,iv:JZ4gkNfNpkzVLH98Ly7aDvZt+Qi0hBjNLDFqnqPUYtM=,tag:ba5StcXZPTNGsolJHSdPvQ==,type:str]
type: ENC[AES256_GCM,data:8UWZA45/,iv:kHCsuyavlBRe3YK63JBQH7lXWWpXXWOWSk2lCQEUXJ0=,tag:et+vNuJKGSsoiyl5kB1DQg==,type:str]
stringData:
    INVENTORY_DATABASE_URL: ENC[AES256_GCM,data:ahEfMtoxt/ZR5Y3KujcyWV4WPShKPWT6igA58OgT8seMSpzbWMq4GJrWqqnOux8iRYxWxrNTki/uM68KhJGUBr07FC95EmhEnRjy2g==,iv:vsFzOgL4I6TWGjH4ySqFjtdMtvg6XGuhy0pP5PvAbYg=,tag:YksvL7BewiWRRC7gLpcXBQ==,type:str]
sops:
    age:
        - recipient: age18p2u2yekx32mhdaea8cpxhvzzld4awa58auh9tdh8wat46pwge2sldmk9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUHVJWTFlVHAxNVRPdGl1
            aitqWFdPQ0trYnA3RmE3dWlxaFBTS0NOamxVCnJWNnJUYkhLSm5CZCtKNTVHMTN2
            Z3FSZEd6bFIyWGZlM1hnRm9GcVRHaFEKLS0tIEVyZlFkbHlhdlc2WG5ic2dDWVYy
            NEFpMmdra2h4K2tHcGtvNHE4aFdEdVUK+QuHrvVKqBEkvCGJSENpBzFOeeAgvziA
            QtLWVgki0pWcAxRXzvlDfI5vhPJqHlQuFOlw1t6qYzUjIT5JFbBDqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:10:51Z"
    mac: ENC[AES256_GCM,data:pUGd+0nVYBuiE0imteUCoy64ApaBgUEprXgxV8UFHVzPELpqVIO53/vjuuq5Ro5m6NkFg+jSSC0Bl6I7ipBrjChpmRH1nK8h6oeZlJE6qujKijYqh73t1xA51peBiVoq8x2iOJtYAvGK+FF6j23YwPPhrXRK7L5jvDSCwgIo2iE=,iv:HLD9hLCh9CQZQQBiTsCh7Zq8VcM5IuwJ3GarI4/plMk=,tag:5oIwan/c/EUeAHDvMOBFpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
