apiVersion: ENC[AES256_GCM,data:oYs=,iv:024dQqix2WfaSROm7rxfCAAa+PQm2JsRNkwuhL11M+4=,tag:6RVNhE9VULscWDwYBP18RA==,type:str]
kind: ENC[AES256_GCM,data:Qcp6+PIL,iv:n1I9AB3ylrJQI+/CY4kBkgsetXY4o/ePKaFfocnpFec=,tag:OdzkjUILCA46K0v0tSroJQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bliskfi+DoZDFCHhoRq6,iv:oyT31yc1C7Mq7AmBiF7H7HRoPceXQhbLEW1uR6owdbw=,tag:tdyUL3kjlxif/6wUcPGn6Q==,type:str]
    namespace: ENC[AES256_GCM,data:W/me8DAqnbX9G8DaHLg=,iv:QvDvFaIMKCwtVv7Xsp6hlVWHCNUwSZm70thVWJZwT4w=,tag:Vgm+YxGJIEHL15Ox4lRV2g==,type:str]
type: ENC[AES256_GCM,data:AZwCLGEt,iv:ehigomUQYqosUQ1K4Ay1wOiYeI1DNZ3Y07tec7sxgLs=,tag:2dpQWDckDvGvCCjO6bJ8+Q==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:60hEX2FW/YIQ,iv:c+5hLoICTTusxRROGbKUIj+fY4yRKHzpX4EZJiUUaNc=,tag:NY4cOBbZGJ97vEBagptV5g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:K6UxGOQWe/jd+zdovg==,iv:lnwkWMsiR0jNzxM7A+Mcn8B6o8VjGlqx2xv4GHjgFI4=,tag:uCLwupY6TNNrJqJ0K/4qZw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+FklTctjSjN8JSKAYtRa+4M=,iv:PN0jvP3ukdYgesO+OwN0NVs7LxTca/rsTmT1wDOzTnE=,tag:t7LFFGYoRU6XK8t/c3s1fg==,type:str]
sops:
    age:
        - recipient: age18p2u2yekx32mhdaea8cpxhvzzld4awa58auh9tdh8wat46pwge2sldmk9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTy82N2h2NU9zTVpKYnl3
            aE5MRWdmNGd2M24ya0hvWktmOFM2b3dQRlVjCjY5Znp0RDVWeGVHWmhOcm5HajhC
            K2dpQ1pXYTVpMGMvdkRqVm9wVVJpMHcKLS0tIGllNDNLV01salVuV0hvTndYeElh
            d0FsM0c5OVhMR1BHNEJoellHN0xpOTAKmheGx6pSqdcLAaqg9c/BmfabD3FHY/o9
            JcC7uvXUXPWPZrC6knH4nOtm8/2YuVBCjHSdkHKFdJaIyX1F0cFZ7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:10:51Z"
    mac: ENC[AES256_GCM,data:uDDZfjYvKWChXZqL4XXw7QgKvaYtUm+t8TB99qsayHlqRlE67DpiL7eBRVZlMk3vOAMxA9th/6k0dQp7KmQiVvj0dv6G3O3T2CciPbudbIcGl1SodbvVgaQrVLEtKqo6LCUM/WuDG7wO3EnH87jr/peBVSSRhlQFTZMMiZBU6VM=,iv:Una2x9eif7XpNR5NvEx375GB13aI/jea4fLWdGnjVLk=,tag:W0h7dCA3TZwrLjuAIZUEug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
