apiVersion: ENC[AES256_GCM,data:z3w=,iv:GjJDiq0Ql+VROSMD63joVjoN11lJkCzTLyR5jmyW4mA=,tag:DURM1H1QmCuuJnFT2kRIAA==,type:str]
kind: ENC[AES256_GCM,data:9DBy2TXq,iv:XqMXhaIf+1ZyqjgKVKdzEXHrtE+1YMSpV6cf7E7N+F0=,tag:rDidvJPJuHTFYR3e6kpAZA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GAhJalK4AoMktlRljkDq,iv:3N14FeSTLyfpfio5KuK95KJBNItYl4sGGjzlvtN3gvc=,tag:STKG5FQ4BOSqQP3BKFhf5Q==,type:str]
type: ENC[AES256_GCM,data:hSsLlOES,iv:O5CIuZv1hVJ+oAATGhA4tyzzhPTneCKDseTKjc4050E=,tag:8ds3/aNbAV5m2rcD041c9A==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:7XyUb9ctI2m5,iv:JJ+YTrnD+WEqqUcKqMX1hkB35/BTi8m52t/DXFe9wSU=,tag:Nd3Ctu+CNAfQs3e0G2HsfQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:ufuu533ZWeg=,iv:CQI8hvzmD8riRQcyrZJRMHLHkVVMpqMyqTQACItvC4c=,tag:gVoaRb5SWWsyOh71BB4zNA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:O9Es45voYE9Ux26sgQSJh7072ZiMNGCl0E4F7nA7Ku8=,iv:ApGL8H5EkWWmazIDyM8/TRyn93aI6q+Vyw8j3ayd1Vs=,tag:r4vfJYHFqYfmuJG5N1a8kQ==,type:str]
sops:
    age:
        - recipient: age1t23p7nly2j9awclcj7fh0c9yu3u3qt3sz9fmkryq7tenwyv9ncmq73tggy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVVl6L1VOeCtmL3lRSTNM
            WGZkMmFuc3ZtUm51dXdSekozLzBpY0MrQlhNCnExYzl5SDVWbjcvbjY1RmhGSUtk
            TVZYeU8zTlRINFdpWEdrdUJLUk9WcnMKLS0tIFJVdnhzdGJnek9IZmJvOHd2VDQy
            bHlNM3RIT2lid20zZ2RtNlRTVG5MbWsK35hPNZfVUVbVSPEDvp87xD7IyusroUWn
            TUsZ6TFxgPPdXDqSia9ko1baVX0uzYcvcJt5dF2SfpgfHNt3+8cR9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T14:34:58Z"
    mac: ENC[AES256_GCM,data:mIMAZmDLTeY26G0a0dlfjn3wFjcTU49HGADYJX/CMHcT2hWOtSirCc0c1rmeAAHngbdBo2oogueWpGcWfvWaNgxcB9qZrA99VioMVOYJ6nhziPBBF3fPBdugOfj5IEzelNY7XmbzHFTj37odxYq82wHTxor2xWEoJiIIUOEcQQk=,iv:zum9ppN3HILrsQ+kZceoU4Yj6gprGzT/YJtCav84VRQ=,tag:kusIavEzyajZARf2UGYR2g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
