apiVersion: ENC[AES256_GCM,data:NtE=,iv:ycufY95YK8zkpYPRBwNTT3PLThwZhBIcbiZ0mB5DjJs=,tag:N55FfAUd0tDCS34Fkqym6A==,type:str]
kind: ENC[AES256_GCM,data:uy8yauX7,iv:HuSdHLlXpfVDSSz/gR1P6to2qClOQul94Q1Ox4v9kGs=,tag:X44G4t8JOEAoVFQggtyIiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JozEIMaYQbOT4sHXwgz4,iv:vTy8P9BBq1XYBme2vhbMynk1dQmOxVaTemvoS+P2Ia8=,tag:ggqhQdOACQJblQoToyrXIQ==,type:str]
    namespace: ENC[AES256_GCM,data:6PALPJFlJvocc96ZIDg=,iv:W51grqa392iX6KahfTUXQLKjo341cuerXv06GPrGbrU=,tag:fJKGcO27N0Ki4i0fSG4VQg==,type:str]
type: ENC[AES256_GCM,data:ILJyYWh3,iv:Mi0Me3cjU/aW7hpOk0jJnYJQmoEB/FGgkaNL5q9BbA8=,tag:v9JkH2QtS/RKi0agbC0PAg==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:9YKnpa7Cj8Nz,iv:ltQpo4xNqh5S+X7p7dD2WOB1NWjUQMKPD9j9WpC8Faw=,tag:0V/PAE8N8/q9GE1RwNhk3w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Hlbt/d4fkeuBUc9yVA==,iv:ow/jNB+fossCH0rpKZbGCDVMr9uIXOXFIU3faU7uvvI=,tag:8HJw83Ij2RDcivPV01LU3A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Y/pOOu+WS8OiExUKQF5UKmVhOWY2lm8=,iv:WG9V4HfNEJ4cVn/WKEabCem9Ny6FJyqMCE8zwAFHSpo=,tag:zfSTZy/Kd8QdpN4z5ZbG7A==,type:str]
sops:
    age:
        - recipient: age18p2u2yekx32mhdaea8cpxhvzzld4awa58auh9tdh8wat46pwge2sldmk9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArb0NIUjFRWkkxbmkxVWpE
            S3pFQWFjTEdzZE0yRzBOV2FkUjFPeUxSOEdBCmM2Z1VqTUJVSzBOcExmcVcxaER4
            R2NEZUMzQW5DYlhXMFhkWGtTL2FOR2cKLS0tIDdkUmlwcnE4R1d5ZWtNRzBjY1ZN
            L2lJN1o4NVhEZEdVa1o1dkYrOE9xTkEKXOqRmeEJ8ri3fbVy7zGohSFyOTrYxYBd
            p0EakqEioP7Vmwc80lTjmFszoIKcqGx1Rx3zxznQZEGEDB48kozyUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:20:40Z"
    mac: ENC[AES256_GCM,data:4KRrsAkFR6vxze476AIXimZllkjV6zEUH2kERJehd+3/TT92Bute36h6+91cJtdQSC1Kewsu+RboHfozEAgW6PaVnQFtYL07fE53qhVkXeEp0+biT66Dvp/JBtgrMuTX4fea6iXRrfwwYdZMtkOCZnu9EAOwVqikYOPotnGF/wc=,iv:Wr4U4jvbeTNnqCk5i+NTVONE2ePQvAx32ISWoq4pbFI=,tag:NptJWmDUUl5aFEj0aKmqxQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
