- op: add
  path: /spec/ingress/0/from/-
  value:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: istio-system
    podSelector:
      matchLabels:
        app: atlas-platform-istio-ingress
        istio: atlas-platform-istio-ingress
