apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - upstream/install-v2.13.3.yaml
  - cmp/ksops-plugin-configmap.yaml

patches:
  - path: patches/repo-server-ksops-sidecar.yaml
    target:
      kind: Deployment
      name: argocd-repo-server
  - path: patches/redis-image.yaml
    target:
      kind: Deployment
      name: argocd-redis
