apiVersion: v1
kind: Namespace
metadata:
  name: atlas-platform-staging
  labels:
    app.kubernetes.io/part-of: atlas-platform
    atlas-platform.io/environment: staging
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
