apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ingress.yaml

patches:
  - path: networkpolicy-patches/web-ingress-from-traefik.yaml
    target:
      kind: NetworkPolicy
      name: web
  - path: networkpolicy-patches/inventory-service-ingress-from-traefik.yaml
    target:
      kind: NetworkPolicy
      name: inventory-service
