apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - require-container-resources.yaml
  - require-container-security-context.yaml
  - require-probes.yaml
  - require-pod-security-basics.yaml
