apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - block-dev-istio-resources.yaml
  - require-istio-infra-core-resources.yaml
  - require-staging-mesh-onboarding.yaml
  - require-container-resources.yaml
  - require-container-security-context.yaml
  - require-probes.yaml
  - require-pod-security-basics.yaml
