apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlas-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: atlas.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: inventory-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
    - host: api.atlas.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: inventory-service
                port:
                  number: 8000
