apiVersion: ENC[AES256_GCM,data:Gog=,iv:+I0Y2E5GTnTTbNzahhbtTFRkfpo0rm3K5c/NOTy3HBo=,tag:bZlh5/P0pRJZqrkksIlX7w==,type:str]
kind: ENC[AES256_GCM,data:zbxjbA7E,iv:PVtNpuKRukqQwUQBUcbuOgwJJBUwbl3Qut0WAk2qtEM=,tag:wtvQxZs80DlmiX+oG+Gtrg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gUhoR051cwcD/0jGZg5Wlr8=,iv:CGUgY/+1ctnE/QUbnUBZnMTdBvW0P1MpUmt2qjwoZ4U=,tag:uQJfO5Ra+rIiQknq2XrJsg==,type:str]
type: ENC[AES256_GCM,data:6l5Ja3HW,iv:NC5/WHZtc3zeMu4U9t84S4EC9X9X8opItx02GZoceG4=,tag:YnhQNXAZXL/Dj9h+yu6ppQ==,type:str]
stringData:
    INVENTORY_DATABASE_URL: ENC[AES256_GCM,data:KLZmOfwBsookhrVGIDSz0aV29vPpuTnOx7C7ybO1RieVvIo+AzJUlnpf8QSw/gFniJ9uj+ct8ktUNvGZJZ6/nfOfNQycCd4fBcVHyRDkvqU3GnhPGr4=,iv:EHMgE50iX6YKIgCdew9dzp9v1yqZWiAicxraEqrsW08=,tag:S3/Xna4sRxBrNQpIUdII4w==,type:str]
sops:
    age:
        - recipient: age1t23p7nly2j9awclcj7fh0c9yu3u3qt3sz9fmkryq7tenwyv9ncmq73tggy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WHkxRkpjUUVrWjhBODVS
            bnVTSzlGYk5vZitZOWlkM1BWdDBZdG5UdVZnCmtGRmRweFhmM0dEaDZFRmlUaHFj
            My9ncGtkVUpCajlOVUdJL3RKaW1GOFUKLS0tIGN1bHVYWkM4RE9VdklCWGVscEU4
            U3d5VXNaMnNGUUJsaklxanhvZE1BQVUKlbS+EYQhUivdwfBp0fbDXxjj/prwu8oh
            Qpmf8wt3VNk0agXPwXKBsg6ePm3P2SrnrlRiEzwF80eDdAVkOb9Oxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T14:34:58Z"
    mac: ENC[AES256_GCM,data:/b3l1egtjT+ME3/4WzyFgdNXUtonwL3/v1jbEVmpKlDHRfe/pArE46TupGcBOwxlz5IArMhsgVrbet7guNF8qbc10mIGCfwtsJVbFyhbQ3kBRtzKj99QWXpsSMLmLpkeRpsPTuM5Ap/iSTnAQVnWs0c0ITtlAclM4CMwpt++bKw=,iv:04T1HoJZ80CmzU/tJa3GWl6C/FWFFMKOFWgPdKg36vc=,tag:OfUXz/zlMtnvC85ZWu40Ew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
