apiVersion: ENC[AES256_GCM,data:ivk=,iv:00N89/vt4RUkoS8ZmawWfO5JmvSxw3ei2LUMDsnOl5w=,tag:U+hseW6/vsYhm598aYWn2Q==,type:str]
kind: ENC[AES256_GCM,data:tPGNYdEf,iv:R7+Ua8DR71BQ6elMqzPTu9dGzZaGS/mtUzNtOHMVzUI=,tag:X/Did8VSpRzblXY+B6SWjA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HLeYlgG8LCsFQbPhmJL9,iv:TZKkWcY/9GrnTen2362yKurWaGQC33FxWz0qzaNn48E=,tag:+E4A8Ow2sNPGeUoaSiYlLw==,type:str]
type: ENC[AES256_GCM,data:egFexSDj,iv:6M+NQSlFQ1R2OXRNivdCx9R4B5aTEScYD9wtSjJZEyo=,tag:IqXjlIr9j1rLjDEqnL5ytw==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:9VPV7UmP9nyc,iv:HNzsx9JJhTnggjP7pPY/MVKu8TdH79vjaIBjwiPchNQ=,tag:G0QAGlc37eZPkrvItmWPjQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:JOYtyMtoQII=,iv:igJPK/vJbN7b5a7RF5WYev0RyNL06VURiKvY00vlP48=,tag:oTel39XYXkWUcq2ScCc9nQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:C7cfZoYqOZizrDXlKiPIPegagbGB2lLdVLy9DiYY4t0=,iv:GHWjAUhWStP1Qo4M694DvE4jFGzcz80tQiAVmyvyIMM=,tag:1Dp1yeVjvpFXPjFhuOgmCg==,type:str]
sops:
    age:
        - recipient: age1t23p7nly2j9awclcj7fh0c9yu3u3qt3sz9fmkryq7tenwyv9ncmq73tggy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbkZ1d1NKY3RxclpFUTd2
            Y3AxbGpKdStWQUZ3T1VIMGJ3eEQ4TGttd1cwClJKODUxTmIyYzEwVHlWQllXUlZM
            VW1DQ1lEa2k2R3FLVGV6TlIzSmdTUU0KLS0tIEJ5Z0gvNU9QRGNFViswZE5QbHd5
            b2xJVEpBb1ByOElKVDFqa2JkakVGb00KC284wWdNManiHi++jCmC1KXuro1wTcL0
            1RluAH72e08PV71vLfg7jtQ0CXcYWV4LqQWVIapsdHb9xokMHkuIMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T14:34:58Z"
    mac: ENC[AES256_GCM,data:mAcokitBDi6fiznDLb5AxPY2jmNq4xn2yu49/DKTYeVoakYfkysjxJPF/j4HlhPvAQ2savzMWaY6ao0ka70SzAkjammlNZClOrC3Iv6g/vXsT2XK+9ZCsQzy1kGyE61jN2uW8aNuzHv53QnwYUj6dDDiFoHxKv8QASeaVaCVvHw=,iv:Y7AfOMBjQ6/CHjnx/t+P02O++PMASg7NO/XjFgzxqWM=,tag:Wbi2iA1rxJeibA9DCmYhVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
