kube-prometheus-stack:
  grafana:
    enabled: false

  alertmanager:
    enabled: false

  kubeStateMetrics:
    enabled: false

  nodeExporter:
    enabled: false

  defaultRules:
    create: false

  prometheusOperator:
    admissionWebhooks:
      enabled: false

  prometheus:
    service:
      type: ClusterIP
    prometheusSpec:
      retention: 24h
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
