kube-prometheus-stack:
  grafana:
    enabled: false

  alertmanager:
    enabled: false

  prometheus-node-exporter:
    enabled: false

  kube-state-metrics:
    enabled: false

  prometheus:
    service:
      type: ClusterIP
    prometheusSpec:
      retention: 24h
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
