apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-platform-istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: atlas-platform-infra
  source:
    repoURL: git@github.com:albersg/atlas-platform.git
    targetRevision: main
    path: platform/helm/istio/istiod
    helm:
      valueFiles:
        - values-common.yaml
        - values-staging-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: istio-sidecar-injector
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
        - .webhooks[]?.failurePolicy
