apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: atlas-platform-infra
  namespace: argocd
spec:
  description: Atlas platform add-ons managed through Helm and Argo CD.
  sourceRepos:
    - git@github.com:albersg/atlas-platform.git
  destinations:
    - namespace: istio-system
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: apiregistration.k8s.io
      kind: APIService
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: apps
      kind: DaemonSet
    - group: apps
      kind: StatefulSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: batch
      kind: Job
    - group: policy
      kind: PodDisruptionBudget
    - group: monitoring.coreos.com
      kind: Alertmanager
    - group: monitoring.coreos.com
      kind: PodMonitor
    - group: monitoring.coreos.com
      kind: Probe
    - group: monitoring.coreos.com
      kind: Prometheus
    - group: monitoring.coreos.com
      kind: PrometheusRule
    - group: monitoring.coreos.com
      kind: ServiceMonitor
    - group: monitoring.coreos.com
      kind: ThanosRuler
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
